const books = [
  // ── Roman ──────────────────────────────────────────────────────────────────
  { id: 1,  title: "Le Petit Prince",                          author: "Antoine de Saint-Exupéry", genre: "Roman",                 rating: 5, isbn: "9780156013987", description: "Un aviateur échoué dans le désert rencontre un mystérieux petit prince venu d'une autre planète. Un conte poétique sur l'amitié, la perte et ce que les adultes oublient en grandissant." },
  { id: 2,  title: "L'Étranger",                               author: "Albert Camus",             genre: "Roman",                 rating: 4, isbn: "9780679720201", description: "Meursault, un homme indifférent au monde qui l'entoure, tue un Arabe sur une plage algérienne. Un roman fondateur de l'absurde, glacial et lumineux à la fois." },
  { id: 3,  title: "Les Misérables",                           author: "Victor Hugo",              genre: "Roman",                 rating: 5, isbn: "9780451419439", description: "Jean Valjean, ancien bagnard, cherche à se racheter dans une France du XIXe siècle déchirée par la misère et l'injustice. Une fresque monumentale sur la rédemption et la dignité humaine." },
  { id: 4,  title: "Madame Bovary",                            author: "Gustave Flaubert",         genre: "Roman",                 rating: 4, isbn: "9780140449129", description: "Emma Bovary, épouse d'un médecin de campagne, rêve d'une vie romanesque que la réalité lui refuse. Le portrait implacable d'une femme étouffée par ses illusions et son époque." },
  { id: 5,  title: "Cherub - The Recruit",                     author: "Robert Muchamore",         genre: "Roman",                 rating: 5, isbn: "206536",        series: "Cherub", volume: 1, description: "James, 12 ans, intègre CHERUB, une organisation secrète de renseignement britannique composée uniquement d'enfants. Une série d'espionnage haletante qui ne prend pas ses lecteurs pour des gamins." },
  { id: 6,  title: "Cherub - Mission 2",                       author: "Robert Muchamore",         genre: "Roman",                 rating: 5, isbn: "9780340881545", series: "Cherub", volume: 2 },
  { id: 50, title: "Cherub - Mission 3 : Arizona Max",         author: "Robert Muchamore",         genre: "Roman",                 rating: 5, isbn: "9782203192744", series: "Cherub", volume: 3 },
  { id: 51, title: "Cherub - Mission 4 : Chute libre",         author: "Robert Muchamore",         genre: "Roman",                 rating: 5, isbn: "9782203020672", series: "Cherub", volume: 4 },
  { id: 52, title: "Cherub - Mission 5 : Mauvaise herbe",      author: "Robert Muchamore",         genre: "Roman",                 rating: 5, isbn: "9782203030022", series: "Cherub", volume: 5 },
  { id: 53, title: "Cherub - Mission 6 : Homme contre bête",   author: "Robert Muchamore",         genre: "Roman",                 rating: 5, isbn: "9782203004221", series: "Cherub", volume: 6 },
  { id: 54, title: "Cherub - Mission 7 : La Chute",            author: "Robert Muchamore",         genre: "Roman",                 rating: 5, isbn: "9782203004238", series: "Cherub", volume: 7 },
  { id: 55, title: "Cherub - Mission 8 : Mad Dogs",            author: "Robert Muchamore",         genre: "Roman",                 rating: 5, isbn: "9782203035331", series: "Cherub", volume: 8 },
  { id: 56, title: "Cherub - Mission 9 : Le Somnambule",       author: "Robert Muchamore",         genre: "Roman",                 rating: 5, isbn: "9780340931837", series: "Cherub", volume: 9 },
  { id: 57, title: "Cherub - Mission 10 : Le Général",         author: "Robert Muchamore",         genre: "Roman",                 rating: 5, isbn: "9780340931844", series: "Cherub", volume: 10 },
  { id: 58, title: "Cherub - Mission 11 : Ange Gardien",       author: "Robert Muchamore",         genre: "Roman",                 rating: 5, isbn: "9780340999226", series: "Cherub", volume: 11 },
  { id: 59, title: "Cherub - Mission 12 : Vague de choc",      author: "Robert Muchamore",         genre: "Roman",                 rating: 5, isbn: "9780340956472", series: "Cherub", volume: 12 },
  { id: 7,  title: "L'Épouvanteur Tome 1",                     author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "13580239",       series: "L'Épouvanteur", volume: 1, description: "Thomas Ward devient l'apprenti de l'Épouvanteur, un vieux sorcier chargé de protéger le Comté des créatures des ténèbres. Une série de dark fantasy médiévale, atmosphérique et addictive." },
  { id: 8,  title: "L'Épouvanteur Tome 2",                     author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "9782747080576", series: "L'Épouvanteur", volume: 2 },
  { id: 60, title: "L'Épouvanteur Tome 3",                     author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "9782747017237", series: "L'Épouvanteur", volume: 3 },
  { id: 61, title: "L'Épouvanteur Tome 4",                     author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "9782747083843", series: "L'Épouvanteur", volume: 4 },
  { id: 62, title: "L'Épouvanteur Tome 5",                     author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "9782747027977", series: "L'Épouvanteur", volume: 5 },
  { id: 63, title: "L'Épouvanteur Tome 6",                     author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "9782747027984", series: "L'Épouvanteur", volume: 6 },
  { id: 64, title: "L'Épouvanteur Tome 7",                     author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "9782747034579", series: "L'Épouvanteur", volume: 7 },
  { id: 65, title: "L'Épouvanteur Tome 8",                     author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "9782747037013", series: "L'Épouvanteur", volume: 8 },
  { id: 66, title: "L'Épouvanteur Tome 9",                     author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "9782747045018", series: "L'Épouvanteur", volume: 9 },
  { id: 67, title: "L'Épouvanteur Tome 10",                    author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "9782747038577", series: "L'Épouvanteur", volume: 10 },
  { id: 68, title: "L'Épouvanteur Tome 11",                    author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "9782747038584", series: "L'Épouvanteur", volume: 11 },
  { id: 69, title: "L'Épouvanteur Tome 12",                    author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "9781782300151", series: "L'Épouvanteur", volume: 12 },
  { id: 70, title: "L'Épouvanteur Tome 13",                    author: "Joseph Delaney",           genre: "Roman",                 rating: 4, isbn: "9781849414715", series: "L'Épouvanteur", volume: 13 },
  { id: 39, title: "Manon Lescaut",                            author: "Abbé Prévost",             genre: "Roman",                 rating: 4, isbn: "9782070413119", description: "Le chevalier Des Grieux sacrifie tout — famille, honneur, avenir — pour une jeune femme volage et irrésistible. Un roman d'amour fatal qui n'a rien perdu de sa puissance." },
  { id: 40, title: "La Peau de chagrin",                       author: "Honoré de Balzac",         genre: "Roman",                 rating: 4, isbn: "9782070413607", description: "Raphaël de Valentin reçoit un talisman qui exauce tous ses désirs, mais rétrécit à chaque vœu — raccourcissant d'autant sa vie. Une fable sur la jeunesse, l'ambition et le prix du bonheur." },
  { id: 41, title: "Sido suivi de Les Vrilles de la vigne",    author: "Colette",                  genre: "Roman",                 rating: 4, isbn: "9782070361175", description: "Colette rend hommage à sa mère Sido et à l'enfance lumineuse de sa Bourgogne natale. Une prose sensorielle et intime, parmi les plus belles de la littérature française." },

  // ── Fantasy ────────────────────────────────────────────────────────────────
  { id: 9,  title: "Harry Potter T.1",                         author: "J.K. Rowling",             genre: "Fantasy",               rating: 5, isbn: "9780439708180", series: "Harry Potter", volume: 1, description: "Harry Potter découvre le jour de ses onze ans qu'il est un sorcier et intègre Poudlard, une école de magie. Le début d'une saga qui a redéfini la fantasy pour toute une génération." },
  { id: 10, title: "Harry Potter T.2",                         author: "J.K. Rowling",             genre: "Fantasy",               rating: 4, isbn: "9780439064873", series: "Harry Potter", volume: 2 },
  { id: 11, title: "Harry Potter T.3",                         author: "J.K. Rowling",             genre: "Fantasy",               rating: 5, isbn: "9780439136365", series: "Harry Potter", volume: 3 },
  { id: 12, title: "Le Seigneur des Anneaux",                  author: "J.R.R. Tolkien",           genre: "Fantasy",               rating: 5, isbn: "9780618640157", series: "Le Seigneur des Anneaux", volume: 1, description: "Frodon Sacquet hérite d'un anneau unique forgé par le Seigneur des Ténèbres pour dominer tous les peuples de la Terre du Milieu. L'œuvre fondatrice de la fantasy moderne, d'une richesse mythologique incomparable." },
  { id: 13, title: "Le Hobbit",                                author: "J.R.R. Tolkien",           genre: "Fantasy",               rating: 5, isbn: "9780345339683", description: "Bilbo Sacquet, hobbit paisible, est entraîné par le magicien Gandalf dans une aventure épique pour reprendre le trésor d'un dragon. Le prélude enchanteur à l'univers de la Terre du Milieu." },
  { id: 14, title: "Les Deux Tours",                           author: "J.R.R. Tolkien",           genre: "Fantasy",               rating: 5, isbn: "9780618346264", series: "Le Seigneur des Anneaux", volume: 2 },
  { id: 15, title: "Le Retour du Roi",                         author: "J.R.R. Tolkien",           genre: "Fantasy",               rating: 5, isbn: "9780618346257", series: "Le Seigneur des Anneaux", volume: 3 },
  { id: 16, title: "Twilight",                                 author: "Stephenie Meyer",          genre: "Fantasy",               rating: 4, isbn: "12641959",       series: "Twilight", volume: 1, description: "Bella Swan s'installe dans la petite ville pluvieuse de Forks et tombe amoureuse d'Edward Cullen, un vampire centenaire. Une romance surnaturelle devenue phénomène mondial." },
  { id: 17, title: "A Game of Thrones",                        author: "George R.R. Martin",       genre: "Fantasy",               rating: 5, isbn: "9780553573404", description: "Sept grandes familles se disputent le Trône de Fer dans un royaume médiéval où les saisons durent des années. Une fantasy politique et brutale, sans héros invincibles ni happy end garanti." },

  // ── Science-Fiction ────────────────────────────────────────────────────────
  { id: 18, title: "1984",                                     author: "George Orwell",            genre: "Science-Fiction",       rating: 5, isbn: "9780451524935", description: "Dans un État totalitaire qui réécrit l'histoire en temps réel, Winston Smith ose penser librement. La dystopie de référence, dont le vocabulaire a envahi notre monde réel." },
  { id: 19, title: "Dune",                                     author: "Frank Herbert",            genre: "Science-Fiction",       rating: 4, isbn: "9780441013593", series: "Dune", volume: 1, description: "Sur Arrakis, planète désertique seule source de l'épice la plus précieuse de l'univers, Paul Atréides devient l'homme dont la légende était attendue depuis des siècles. Une épopée politique, écologique et mystique sans équivalent en SF." },
  { id: 20, title: "Dune Messiah",                             author: "Frank Herbert",            genre: "Science-Fiction",       rating: 4, isbn: "9780441172696", series: "Dune", volume: 2 },
  { id: 21, title: "Le Meilleur des Mondes",                   author: "Aldous Huxley",            genre: "Science-Fiction",       rating: 4, isbn: "9780060850524", description: "Dans un futur où le bonheur est garanti par le conditionnement génétique et les drogues légales, un « sauvage » découvre ce que l'humanité a sacrifié. Une dystopie plus troublante que jamais à l'heure du transhumanisme." },
  { id: 22, title: "Fahrenheit 451",                           author: "Ray Bradbury",             genre: "Science-Fiction",       rating: 4, isbn: "9781451673319", description: "Dans une société où les livres sont interdits et brûlés par des pompiers, Guy Montag commence à douter. Un roman-manifeste sur la censure et le pouvoir des mots." },
  { id: 23, title: "Fondation",                                author: "Isaac Asimov",             genre: "Science-Fiction",       rating: 5, isbn: "9780553293357", description: "Hari Seldon, mathématicien génial, prédit l'effondrement de l'Empire Galactique et fonde une organisation pour préserver le savoir humain. Le monument de la SF classique, visionnaire et rigoureusement construit." },

  // ── Manga ──────────────────────────────────────────────────────────────────
  { id: 24, title: "Naruto Vol.1",                             author: "Masashi Kishimoto",        genre: "Manga",                 rating: 5, isbn: "9781569319000", series: "Naruto", volume: 1, description: "Naruto Uzumaki, jeune ninja rejeté de son village car porteur d'un démon renard, rêve de devenir Hokage. Le shōnen de référence sur l'amitié, la persévérance et la rédemption." },
  { id: 25, title: "Death Note Vol.1",                         author: "Tsugumi Ohba",             genre: "Manga",                 rating: 5, isbn: "9781421501697", series: "Death Note", volume: 1, description: "Light Yagami trouve un carnet qui tue toute personne dont le nom y est inscrit. Un duel psychologique haletant entre un lycéen mégalomane et le détective le plus brillant du monde." },
  { id: 26, title: "Fullmetal Alchemist Vol.1",                author: "Hiromu Arakawa",           genre: "Manga",                 rating: 5, isbn: "9781591164418", series: "Fullmetal Alchemist", volume: 1, description: "Deux frères alchimistes cherchent la Pierre Philosophale pour retrouver leurs corps perdus lors d'une transmutation interdite. Un manga d'aventure et de philosophie, parfaitement rythmé." },
  { id: 27, title: "Dragon Ball Vol.1",                        author: "Akira Toriyama",           genre: "Manga",                 rating: 5, isbn: "9781569319208", series: "Dragon Ball", volume: 1, description: "Son Goku, enfant à la queue de singe, part à la recherche des sept Dragon Balls avec la jeune Bulma. L'œuvre fondatrice du manga de combat, drôle et inventive avant tout." },
  { id: 71, title: "666 Satan Vol.1",                          author: "Seishi Kishimoto",         genre: "Manga",                 rating: 4, isbn: null,            series: "666 Satan", volume: 1, description: "Ruby et Jio, deux jeunes chercheurs d'O-Parts, des artefacts anciens dotés de pouvoirs extraordinaires, parcourent un monde post-apocalyptique. Un shōnen intense signé du frère de Masashi Kishimoto." },
  { id: 28, title: "666 Satan Vol.2",                          author: "Seishi Kishimoto",         genre: "Manga",                 rating: 4, isbn: "9788483579329", series: "666 Satan", volume: 2 },
  { id: 72, title: "666 Satan Vol.3",                          author: "Seishi Kishimoto",         genre: "Manga",                 rating: 4, isbn: "9788411010344", series: "666 Satan", volume: 3 },
  { id: 73, title: "666 Satan Vol.4",                          author: "Seishi Kishimoto",         genre: "Manga",                 rating: 4, isbn: "9788411011136", series: "666 Satan", volume: 4 },
  { id: 74, title: "666 Satan Vol.5",                          author: "Seishi Kishimoto",         genre: "Manga",                 rating: 4, isbn: "9788411012201", series: "666 Satan", volume: 5 },
  { id: 75, title: "666 Satan Vol.6",                          author: "Seishi Kishimoto",         genre: "Manga",                 rating: 4, isbn: "9788411013666", series: "666 Satan", volume: 6 },
  { id: 76, title: "666 Satan Vol.7",                          author: "Seishi Kishimoto",         genre: "Manga",                 rating: 4, isbn: "9788411014694", series: "666 Satan", volume: 7 },
  { id: 77, title: "666 Satan Vol.8",                          author: "Seishi Kishimoto",         genre: "Manga",                 rating: 4, isbn: "9788411016810", series: "666 Satan", volume: 8 },
  { id: 29, title: "Yureka Vol.1",                             author: "Yi Hyeon-Se",              genre: "Manga",                 rating: 4, isbn: "9788493607357", series: "Yureka", volume: 1, description: "Dans un MMORPG ultra-réaliste, un joueur médiocre se retrouve lié à une guerrière légendaire dont il est le seul à connaître la véritable identité. Un manhwa coréen mélangeant jeu vidéo et romance." },

  // ── Théâtre ────────────────────────────────────────────────────────────────
  { id: 30, title: "Hamlet",                                   author: "William Shakespeare",      genre: "Théâtre",               rating: 5, isbn: "9780743477123", description: "Le prince Hamlet apprend de son père mort que son oncle l'a assassiné pour prendre le trône. La tragédie shakespearienne par excellence, sur la vengeance, la folie et le doute." },
  { id: 31, title: "Roméo et Juliette",                        author: "William Shakespeare",      genre: "Théâtre",               rating: 5, isbn: "9780743477116", description: "Deux jeunes gens de familles ennemies tombent éperdument amoureux dans les rues de Vérone. La plus célèbre histoire d'amour impossible de la littérature occidentale." },
  { id: 32, title: "En attendant Godot",                       author: "Samuel Beckett",           genre: "Théâtre",               rating: 4, isbn: "9780802144423", description: "Vladimir et Estragon attendent Godot, qui ne viendra peut-être jamais. La pièce emblématique du théâtre de l'absurde, aussi drôle que profondément mélancolique." },
  { id: 33, title: "Antigone",                                 author: "Sophocle",                 genre: "Théâtre",               rating: 4, isbn: "9780156036559", description: "Antigone défie le décret royal pour enterrer son frère selon les rites sacrés, au risque de sa vie. Une tragédie grecque intemporelle sur le conflit entre loi divine et loi humaine." },
  { id: 42, title: "Le Malade Imaginaire",                     author: "Molière",                  genre: "Théâtre",               rating: 4, isbn: "9782070380060", description: "Argan, hypocondriaque obsessionnel, veut marier sa fille à un médecin pour avoir des soins gratuits. La dernière comédie de Molière, jouée le soir même de sa mort, entre rire et amertume." },
  { id: 43, title: "Les Fausses Confidences",                  author: "Marivaux",                 genre: "Théâtre",               rating: 4, isbn: "9782070380114", description: "Dorante, ruiné, tente de conquérir la riche veuve Araminte grâce aux manipulations habiles de son valet Dubois. Marivaux au sommet : une comédie sur le désir, le mensonge et les jeux du cœur." },
  { id: 44, title: "Juste la fin du monde",                    author: "Jean-Luc Lagarce",         genre: "Théâtre",               rating: 4, isbn: "9782851813046", description: "Louis rentre dans sa famille après des années d'absence pour leur annoncer sa mort prochaine — mais les mots ne viennent pas. Une pièce sur l'impossibilité de communiquer, d'une précision douloureuse." },

  // ── Policier ───────────────────────────────────────────────────────────────
  { id: 34, title: "Sherlock Holmes",                          author: "Arthur Conan Doyle",       genre: "Policier",              rating: 5, isbn: "9780141040288", description: "Le détective consultant Sherlock Holmes résout les affaires les plus impénétrables grâce à sa logique implacable et son sens de l'observation. Les aventures qui ont inventé le roman policier moderne." },
  { id: 35, title: "Dix Petits Nègres",                        author: "Agatha Christie",          genre: "Policier",              rating: 5, isbn: "9780062073563", description: "Dix inconnus sont invités sur une île isolée et meurent les uns après les autres selon une comptine enfantine. Le roman policier le plus vendu de l'histoire, un puzzle imparable." },
  { id: 36, title: "Da Vinci Code",                            author: "Dan Brown",                genre: "Policier",              rating: 4, isbn: "9780307474278", description: "Un meurtre au Louvre entraîne un professeur d'Harvard dans une course contre la montre pour décoder un message caché dans les œuvres de Léonard de Vinci. Un thriller ésotérique à la mécanique parfaitement huilée." },

  // ── Poésie ─────────────────────────────────────────────────────────────────
  { id: 37, title: "Les Fleurs du Mal",                        author: "Charles Baudelaire",       genre: "Poésie",                rating: 5, isbn: "9780140444445", description: "Baudelaire explore la beauté, le vice, l'ennui et l'idéal à travers une poésie d'une musicalité et d'une densité sans égales. Le recueil qui a transformé la poésie française en ouvrant la voie au symbolisme." },
  { id: 38, title: "Illuminations",                            author: "Arthur Rimbaud",           genre: "Poésie",                rating: 4, isbn: "9780140443820", description: "Des visions hallucinées, des paysages impossibles, une langue fracturée et visionnaire. Rimbaud à 19 ans invente la modernité poétique, avant de tout abandonner." },
  { id: 45, title: "Les Contemplations",                       author: "Victor Hugo",              genre: "Poésie",                rating: 5, isbn: "9782070410712", description: "Hugo réunit vingt-cinq ans de poèmes autour du deuil de sa fille Léopoldine, de l'exil et de la quête de sens. Son chef-d'œuvre lyrique, d'une ampleur et d'une émotion rares." },
  { id: 46, title: "Alcools",                                  author: "Guillaume Apollinaire",    genre: "Poésie",                rating: 4, isbn: "9782070360697", description: "Sans ponctuation, mêlant modernité urbaine et nostalgie romantique, Apollinaire réinvente le poème. Un recueil charnière entre tradition et avant-garde, d'une liberté formelle enivrante." },

  // ── Littérature d'idées ────────────────────────────────────────────────────
  { id: 47, title: "Gargantua",                                author: "François Rabelais",        genre: "Littérature d'idées",   rating: 4, isbn: "9782070360611", description: "Les aventures grotesques et jubilatoires du géant Gargantua servent de prétexte à une critique féroce de l'éducation scolastique et une célébration de l'humanisme renaissant. Rabelais à son meilleur : savant, obscène et libre." },
  { id: 48, title: "Les Caractères",                           author: "Jean de La Bruyère",       genre: "Littérature d'idées",   rating: 4, isbn: "9782070369577", description: "Des portraits au vitriol des courtisans, bourgeois et vaniteux du Grand Siècle. Un regard acéré sur la comédie humaine, étonnamment moderne dans sa lecture des rapports sociaux." },
  { id: 49, title: "Déclaration des droits de la femme",       author: "Olympe de Gouges",         genre: "Littérature d'idées",   rating: 5, isbn: "9782070442300", description: "En 1791, Olympe de Gouges réécrit la Déclaration des droits de l'homme en y incluant les femmes. Un texte fondateur du féminisme, rédigé par une femme qui mourra guillotinée pour ses idées." },
]

export default books
